import ChallengeDetailsCard from "@/components/ChallengeDetailsCard";
import { SafeAreaView } from "react-native-safe-area-context";
// import ChallengeList from "@/components/ChallengeList";

const challenges = [
  {
    id: "1",
    label: "Where is my jet",
    status: "published",
    goal: 100,
    brandId: "1",
    brand: "PepsiCo",
    description: "Recycle 100 Pepsi cans",
    rewards: ["A dream jet", "Pepsi tshirt"],
    product: "Pepsi can",
    user: {
      id: "1",
      email: "arnaud.obri@gmail.com",
    },
    amount: 45,
  },
  {
    id: "2",
    label: "Doritos challenge",
    status: "published",
    goal: 60,
    brandId: "2",
    brand: "Doritos",
    description: "Recycle 60 Doritos bags",
    rewards: ["Giant tacos"],
    product: "Doritos bag",
    user: {
      id: "1",
      email: "arnaud.obri@gmail.com",
    },
    amount: 30,
  },
  {
    id: "3",
    label: "Oreos challenge",
    status: "published",
    goal: 20,
    brandId: "3",
    brand: "Oreos brand",
    description: "Recycle 20 Oreos cookies boxes",
    rewards: ["Giant oreos", "Oreos PS5"],
    product: "Oreos cookies box",
    user: {
      id: "1",
      email: "arnaud.obri@gmail.com",
    },
    amount: 3,
  },
  {
    id: "4",
    label: "Sweet Cookie Quest",
    status: "published",
    goal: 35,
    brandId: "3",
    brand: "Oreos brand",
    description: "Recycle 35 Oreos mini pack containers",
    rewards: ["Limited edition Oreos", "Cookie jar collection"],
    product: "Oreos mini pack",
    user: {
      id: "2",
      email: "maria.santos@email.com",
    },
    amount: 12,
  },
  {
    id: "5",
    label: "Coca-Cola Green Mission",
    status: "published",
    goal: 150,
    brandId: "4",
    brand: "Coca-Cola",
    description: "Recycle 150 Coca-Cola bottles and help save the planet",
    rewards: [
      "Eco-friendly backpack",
      "Coca-Cola vintage collection",
      "Tree planting certificate",
    ],
    product: "Coca-Cola bottle",
    user: {
      id: "3",
      email: "james.wilson@gmail.com",
    },
    amount: 87,
  },
  {
    id: "6",
    label: "McDonald's Happy Meal Hero",
    status: "draft",
    goal: 25,
    brandId: "5",
    brand: "McDonald's",
    description: "Recycle 25 Happy Meal boxes and toys packaging",
    rewards: ["McDonald's gift card €50", "Exclusive Happy Meal toy set"],
    product: "Happy Meal box",
    user: {
      id: "4",
      email: "sophie.martin@outlook.com",
    },
    amount: 8,
  },
  {
    id: "7",
    label: "Starbucks Cup Challenge",
    status: "published",
    goal: 80,
    brandId: "6",
    brand: "Starbucks",
    description: "Recycle 80 Starbucks cups and make a difference",
    rewards: [
      "Reusable Starbucks tumbler",
      "Free coffee for a month",
      "Starbucks merchandise",
    ],
    product: "Starbucks cup",
    user: {
      id: "5",
      email: "alex.brown@yahoo.com",
    },
    amount: 23,
  },
  {
    id: "8",
    label: "Nike Shoebox Sustainability",
    status: "published",
    goal: 40,
    brandId: "7",
    brand: "Nike",
    description: "Recycle 40 Nike shoe boxes and packaging materials",
    rewards: [
      "Nike Air Max sneakers",
      "Nike duffel bag",
      "Nike gift voucher €100",
    ],
    product: "Nike shoe box",
    user: {
      id: "6",
      email: "emma.davis@gmail.com",
    },
    amount: 15,
  },
  {
    id: "9",
    label: "Apple EcoBox Initiative",
    status: "published",
    goal: 30,
    brandId: "8",
    brand: "Apple",
    description: "Recycle 30 Apple product boxes and accessories packaging",
    rewards: [
      "Apple AirPods",
      "Apple Store credit €200",
      "Eco-friendly iPhone case",
    ],
    product: "Apple product box",
    user: {
      id: "7",
      email: "david.garcia@icloud.com",
    },
    amount: 22,
  },
  {
    id: "10",
    label: "Nestlé Water Bottle Mission",
    status: "published",
    goal: 200,
    brandId: "9",
    brand: "Nestlé",
    description: "Recycle 200 Nestlé water bottles for a cleaner environment",
    rewards: [
      "Water filtration system",
      "Nestlé product bundle",
      "Environmental impact certificate",
    ],
    product: "Nestlé water bottle",
    user: {
      id: "8",
      email: "lisa.johnson@hotmail.com",
    },
    amount: 156,
  },
  {
    id: "11",
    label: "Amazon Package Recycler",
    status: "published",
    goal: 75,
    brandId: "10",
    brand: "Amazon",
    description: "Recycle 75 Amazon delivery boxes and packaging materials",
    rewards: [
      "Amazon Echo Dot",
      "Amazon Prime membership extension",
      "€75 Amazon gift card",
    ],
    product: "Amazon delivery box",
    user: {
      id: "9",
      email: "michael.lee@gmail.com",
    },
    amount: 41,
  },
  {
    id: "12",
    label: "Red Bull Energy Recycling",
    status: "published",
    goal: 120,
    brandId: "11",
    brand: "Red Bull",
    description: "Recycle 120 Red Bull cans and give wings to the environment",
    rewards: [
      "Red Bull mini fridge",
      "Extreme sports experience voucher",
      "Red Bull merchandise pack",
    ],
    product: "Red Bull can",
    user: {
      id: "10",
      email: "anna.rodriguez@email.com",
    },
    amount: 67,
  },
  {
    id: "13",
    label: "IKEA Furniture Box Challenge",
    status: "draft",
    goal: 15,
    brandId: "12",
    brand: "IKEA",
    description: "Recycle 15 IKEA furniture boxes and assembly materials",
    rewards: [
      "IKEA gift card €100",
      "Sustainable furniture piece",
      "IKEA family membership perks",
    ],
    product: "IKEA furniture box",
    user: {
      id: "11",
      email: "thomas.anderson@outlook.com",
    },
    amount: 4,
  },
  {
    id: "14",
    label: "Samsung Galaxy Green",
    status: "published",
    goal: 25,
    brandId: "13",
    brand: "Samsung",
    description: "Recycle 25 Samsung product boxes and electronic packaging",
    rewards: [
      "Samsung Galaxy Buds",
      "Samsung wireless charger",
      "Samsung store credit €150",
    ],
    product: "Samsung product box",
    user: {
      id: "12",
      email: "sarah.white@gmail.com",
    },
    amount: 18,
  },
  {
    id: "15",
    label: "Zara Fashion Forward Recycling",
    status: "published",
    goal: 50,
    brandId: "14",
    brand: "Zara",
    description: "Recycle 50 Zara shopping bags and clothing tags",
    rewards: [
      "Zara gift card €200",
      "Sustainable fashion collection piece",
      "Personal styling session",
    ],
    product: "Zara shopping bag",
    user: {
      id: "13",
      email: "carlos.lopez@yahoo.com",
    },
    amount: 31,
  },
  {
    id: "16",
    label: "H&M Conscious Collection",
    status: "published",
    goal: 90,
    brandId: "15",
    brand: "H&M",
    description: "Recycle 90 H&M shopping bags and promote sustainable fashion",
    rewards: [
      "H&M Conscious collection outfit",
      "Fashion sustainability workshop",
      "€100 H&M voucher",
    ],
    product: "H&M shopping bag",
    user: {
      id: "14",
      email: "jennifer.taylor@hotmail.com",
    },
    amount: 52,
  },
  {
    id: "17",
    label: "Adidas Three Stripes Green",
    status: "published",
    goal: 45,
    brandId: "16",
    brand: "Adidas",
    description: "Recycle 45 Adidas shoe boxes and sports equipment packaging",
    rewards: [
      "Adidas Ultraboost sneakers",
      "Adidas sports bag",
      "Adidas store credit €120",
    ],
    product: "Adidas shoe box",
    user: {
      id: "15",
      email: "robert.miller@gmail.com",
    },
    amount: 28,
  },
  {
    id: "18",
    label: "L'Oréal Beauty Recycling",
    status: "draft",
    goal: 65,
    brandId: "17",
    brand: "L'Oréal",
    description: "Recycle 65 L'Oréal beauty product containers and packaging",
    rewards: [
      "L'Oréal beauty product set",
      "Professional makeup consultation",
      "Sustainable beauty kit",
    ],
    product: "L'Oréal container",
    user: {
      id: "16",
      email: "michelle.clark@outlook.com",
    },
    amount: 19,
  },
  {
    id: "19",
    label: "PlayStation Eco Gaming",
    status: "published",
    goal: 20,
    brandId: "18",
    brand: "PlayStation",
    description: "Recycle 20 PlayStation game cases and console packaging",
    rewards: [
      "PlayStation 5 game",
      "PlayStation Store credit €80",
      "Limited edition controller",
    ],
    product: "PlayStation game case",
    user: {
      id: "17",
      email: "kevin.wright@gmail.com",
    },
    amount: 14,
  },
  {
    id: "20",
    label: "Unilever Sustainable Living",
    status: "published",
    goal: 110,
    brandId: "19",
    brand: "Unilever",
    description: "Recycle 110 Unilever product containers from various brands",
    rewards: [
      "Unilever sustainable product bundle",
      "Home sustainability audit",
      "€85 eco-products voucher",
    ],
    product: "Unilever product container",
    user: {
      id: "18",
      email: "patricia.hall@yahoo.com",
    },
    amount: 73,
  },
];

export default function Index() {
  return (
    <SafeAreaView className="bg-white">
      <ChallengeDetailsCard />
      {/* <ChallengeList challenges={challenges} />; */}
    </SafeAreaView>
  );
}
